version: '3'

services:
  core:
    build:
      context: .
      dockerfile: dockerfile
    container_name: le-ploy-core
    restart: unless-stopped
    environment:
      - NUXT_GITHUB_CLIENT_ID=${NUXT_GITHUB_CLIENT_ID:-b0b0b0b0b0b0b0b0b0b0}
      - NUXT_GITHUB_CLIENT_SECRET=${NUXT_GITHUB_CLIENT_SECRET:-b12312qwdaSDasd1123}
      - NUXT_AUTH_JS_SECRET=${NUXT_GITHUB_CLIENT_SECRET:-"b12312qwdaSDasd1123"}
      - NUXT_PUBLIC_AUTH_JS_BASE_URL="http://localhost:3000"
      - APP_ID=${APP_ID}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - PRIVATE_KEY=${PRIVATE_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.bun.rule=Host(`le-ploy.localhost`)
      - traefik.http.routers.bun.entrypoints=web
      - traefik.http.services.bun.loadbalancer.server.port=3000
      - traefik.http.services.bun.loadbalancer.server.scheme=http
    ports:
      - '3000:3000'
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    # networks:
      # - le-ploy

# networks:
#   le-ploy:
#     external: true
