version: '3.8'
services:
  node:
    command: 'npm i -g bun && bun run dev'
    volumes:
      - .:/usr/src/app:cached
    # networks:
    #   - web-dev
    # Remove the ports if you are using something like Trafeik or Caddy (recommended)
    ports:
      - target: 3000
        published: 3000
        mode: host
