
# syntax = docker/dockerfile:1

# Use Node.js as the base image
ARG NODE_VERSION=20.8.0
FROM node:${NODE_VERSION}-slim as node_base

# Set the working directory
WORKDIR /usr/src/app

# Set the environment to production
ENV NODE_ENV=production

# Install packages needed to build node modules
RUN apt-get update -qq && apt-get install -y build-essential openssl libssl-dev pkg-config python-is-python3

# Install Bun
RUN npm install -g bun

# Copy package files and lock files for Bun
COPY package.json bun.lockb ./

# Install dependencies with Bun
RUN bun install --frozen-lockfile

# Copy your source code
COPY . .

# Use npx to run Prisma generate

RUN bun run build

# Expose the port your app runs on
EXPOSE 3000/tcp

# Define the command to run your app using Bun
ENTRYPOINT [ "bun", "run", "start" ] 
